### ISSUE TITLE
Status flags: do not publish unless configured

### ISSUE THREAD

**Issue by x1B** [LaxarJS/ax-messages-widget#12]
Currently, the laxar-messages-widget publishes status flags even when nobody is interested.

To fix this, it would probably be enough to remove the default values in the widget.json, and possibly add some null-handling.

However, this might break applications, so it's a major bump.

**Comment by jonaswjs** [comment]
Implemented on master (v4.0.0)

### Breaking Change

The messages widget does not have a default property for the status flag anymore. Thus it does not publish the status flag unless it is configured. The widget in version less than 4.0.0 publishes the flag with the combined topic `messageStatus-` and the status class, even when the appropriate property of the `features.status` was not configured. To keep the old behavior after an upgrade add the flags for each status class to your page configurations.

Old configuration:
```
{
   "widget": "laxarjs/ax-messages-widget",
   "features": {
     "resource": {
         "list": []
      }
   }
}
```

New configuration *only if needed*:
```
{
   "widget": "laxarjs/ax-messages-widget",
   "features": {
      "resource": {
            "list": []
         },
      "status": {
         "ERROR": "messageStatus-ERROR",
         "WARNING": "messageStatus-WARNING",
         "INFO": "messageStatus-INFO",
         "SUCCESS": "messageStatus-SUCCESS",
         "BLANK": "messageStatus-BLANK"         
      }
   }
}
```
